**Exception Handling**

When Python experiences an exceptional event. This is throwing an exception or raising an exception \\
Raise: We invoke these to trigger exceptions on our terms \\
Throw: Exceptions which were not handled. \\


Raise statement: Manually generate an exception.

Try-Except Block

<code>
try:
   CODE
except __:
   HANDLER CODE
   
finally:
    CLEAN UP
</code>

<code>
**Instantiating an instance of the exception object
raise Exception
** Add extra message
>>> raise Exception('The flux capacitor is broken')
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    raise Exception('The flux capacitor is broken')
Exception: The flux capacitor is broken
</code>

**Call Stack
**

In computer science, a call stack is a stack data structure that stores information about the active subroutines of a computer program. This kind of stack is also known as an execution stack, control stack, run-time stack, or machine stack, and is often shortened to just "the stack".

{{:mani:notes:callstack.png|}}

**Exception Handling Demo
**

<code>
'''
# Division by zero
# Input always comes back with a string object
# We are converting the input string into int
a = int(input('First number, please: '))
b = int(input('Second number: '))
print('You result is ', a/b)
'''

'''
Try- Except block
'''
'''
try:
    a = int(input('First number, please: '))
    b = int(input('Second number: '))
    print('Your result is ', a/b)
except ZeroDivisionError:
    print('Error: Division by zero will not work.')
'''

'''
# Multi-exception handler
'''
'''
try:
    a = float(input('First number, please: '))
    b = float(input('Second number: '))
    print('Your result is ', a/b)
except ZeroDivisionError:
    print('Error: Division by zero will not work.')
except ValueError:
    print('Error: You used an incorrect data type.')
'''

'''
# Print more dynamic exception message text
'''
'''
try:
    a = float(input('First number, please: '))
    b = float(input('Second number: '))
    print('Your result is ', a/b)
    # Order of operations - Python treats the
    # following line as a tuple
except (ZeroDivisionError, ValueError, TypeError) : 
    print('Error: Invalid input provided.')
'''

'''
# Print more dynamic exception message text
'''

'''
try:
    a = float(input('First number, please: '))
    b = float(input('Second number: '))
    print('Your result is ', a/b)
except (ZeroDivisionError, ValueError, TypeError) as e:
    print('Error: ', e)

'''

'''
# Keep program running after an exception
'''
'''
# Keep asking for inputs and throwing exceptions
# if the inputs are wrong
while True:
    try:
        a = float(input('First number, please: '))
        b = float(input('Second number: '))
        print('Your result is ', a/b)
    except :
        print('Invalid input. Please retry',)
# If you get the right input: end!
    else:
        break

'''

'''
Use Finally to cleann up after an exception
'''
# Take two args x and y and divide
def divlog(x,y):
    try:
        # Open a file for appending
        f = open('/home/mani/files/sub/ccna domains.txt', 'a')
        # Braces positional formatting
        # g -> general floating point presentation type
        # print number as a fixed point number
        # Third element x/y
        f.write('{0:g} / {1:g} = {2:g}\n'.format(x, y, (x/y)))
#Unhandled exception will result in abort
    except ZeroDivisionError:
        f.write('Error: Zero division not allowed\n')
        raise
# Finally runs regardless of whether an exception occurs
# Finally runs regarless of the final status of try
    finally:
        f.close()

divlog(100,21)
divlog(20,5)
divlog(10,0)

</code>

**Custom Exceptions
**

We can use base classes to raise custom exceptions as a sub-class of the std.ex.classes.


Note: classes are TEMPLATES.

By creating a custom class that inherits from an already existing class, we have immediate access to all of the methods and classes of that class, we inherited from.
We can make changes to the Base classes and let our custom classes inherit those changes from the base classes. Although, we should not tinker with the base classes though.
Encapsulation will allow us to ride herd with the classes and their methods are available to use using the dot notation.

<code>
class CustomError(Exception)
# pass: null, placeholder statement
# You haven`t done anything in a function but you want to keep it alive
# It will run just fine but will not do anything
      pass
# To use your custom error: you have to import the module containing
# the base class
raise CustomError('Something went kerflunky.')
</code>

<code>
>>> class CustomError(Exception):
	pass

>>> raise CustomError('Something went kerflunky.')
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    raise CustomError('Something went kerflunky.')
CustomError: Something went kerflunky.
</code>

<code>
# Class Definition for a custom error
class MyError(Exception):
    # INIT function
    # Constructor
    # Constructor is the engine for creating
    # an instance of the class
    # self - python (private)
    # value - user supplied
    def __init__(self, value):
        # Value of our input parameter
        self.value = value
    # STR - String representation of an object
    # if we run string function against an instance
    # of the MyError class.
    # To make the information provided to us
    # helpful to us, we need to avoid information
    # like this is an object of my error.
    # We are returning a representation.
    def __str__(self):
        # Representation
        # We will represent what was given by the user
        # as a value
        return repr(self.value)

try:
    # Value being passed to the instance is 2*2
    raise MyError(2*2)
# Capture MyError as name e
except MyError as e:
    print('My Error occurred, value:', e.value)

</code>